In [2]:
import numpy as np

In [3]:
a = np.random.default_rng(seed=40)

b = a.integers(0, 101, (5, 5))

b[b > 50] = 0

print(b)

[[ 0  0  2  0 44]
 [ 0  3  6 47  0]
 [ 7  0  0 48  5]
 [34  0  0  0  0]
 [ 0 11  0 10 36]]


In [4]:
a = np.random.default_rng(seed=40)

b = a.integers(0, 10, (4, 3))

print(b)

c = b.sum(axis=0)

print(c)

d = b / c

print(d)

[[5 7 0]
 [6 4 9]
 [0 0 4]
 [6 0 9]]
[17 11 22]
[[0.29411765 0.63636364 0.        ]
 [0.35294118 0.36363636 0.40909091]
 [0.         0.         0.18181818]
 [0.35294118 0.         0.40909091]]


In [5]:
a = np.array([2, 5, 1])

b = np.array([4, 1, 7])

c = np.sqrt(((a - b) ** 2).sum())

d = np.linalg.norm(a - b)

print(c)

print(d)

7.483314773547883
7.483314773547883


In [6]:
import time

a = np.arange(1_000_000)

start = time.time()

b = a**2 + 2*a + 1

end = time.time()

print("Vectorized Time:", end - start)

start = time.time()

c = []

for i in a:
    c.append(i**2 + 2*i + 1)

end = time.time()

print("For Loop Time:", end - start)

Vectorized Time: 0.03155851364135742
For Loop Time: 0.735358715057373


In [7]:
a = np.random.default_rng(seed=40)

b = a.random((10, 3))

c = a.integers(0, 3, 10)

d = np.argmax(b, axis=1)

f = np.mean(d == c)

print(b)
print(c)
print(d)
print(f)

[[0.7298985  0.69341496 0.94192102]
 [0.05965206 0.69052097 0.92239752]
 [0.47568318 0.33839069 0.60188281]
 [0.73062776 0.11226259 0.10862828]
 [0.63726129 0.04232872 0.04771339]
 [0.31927198 0.21120551 0.77624585]
 [0.79724132 0.17178832 0.13999837]
 [0.37004317 0.52964165 0.54236503]
 [0.38012403 0.43165694 0.36066174]
 [0.27451715 0.62069279 0.26930308]]
[2 1 2 1 2 0 2 1 2 0]
[2 2 2 0 0 2 0 2 1 1]
0.2
